name: Build And Upload Artifact
on:
  workflow_call:
    inputs:
      branch:
        required: false
        default: ""
        type: string
      artifactName:
        required: true
        type: string

jobs:
  build-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: actions/setup-node@
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm build

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
          path: dist
