# ref: https://zenn.dev/odan/articles/94d9173da1eac2

name: Try Auto Merge
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-and-upload-artifact-on-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: pnpm/action-setup@v2
        with:
          version: 8.12.1
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install
      - run: pnpm build

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-main
          path: dist

  build-and-upload-artifact-on-topic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.12.1
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install
      - run: pnpm build

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-topic
          path: dist

  check-build-diff:
    needs:
      - build-and-upload-artifact-on-main
      - build-and-upload-artifact-on-topic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}-main
          path: dist-main
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}-topic
          path: dist-current

      - id: diff-name-only
        uses: gh640/command-result-action@v1
        with:
          command: diff -qr dist-main dist-topic
